apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-rag-assistant
  labels:
    app: local-rag-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-rag-assistant
  template:
    metadata:
      labels:
        app: local-rag-assistant
    spec:
      containers:
      - name: app
        image: local-rag-assistant:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: index
          mountPath: /app/index
        - name: cache
          mountPath: /app/cache
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rag-data-pvc
      - name: index
        persistentVolumeClaim:
          claimName: rag-index-pvc
      - name: cache
        persistentVolumeClaim:
          claimName: rag-cache-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: rag-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: local-rag-assistant-service
spec:
  selector:
    app: local-rag-assistant
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-index-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 